#!/usr/bin/perl -w

package main;

our $VERSION = substr q$Revision: 0.1 $, 10;

### Modules & pragmas

use Getopt::Long;

#############################################################################
### Configuration

### Command paths (Full or relative paths accepted)


### Preferences

# [Optional] Turns on debugging
our $DEBUG = 1;

### End Configuration
#############################################################################


#############################################################################
### Init

### Usage

sub usage
{
  print STDERR
"Usage: $arg0 [-h] [-d dummy] [file...]
       -h: displays help
       -d dummy: you're a dummy
";
  exit 1;
}

### Options

my $opt_help;
my $opt_dummy = "dummy";

Getopt::Long::Configure( "no_ignore_case" );
GetOptions(
  "h" => \$opt_help,
  "d" => \$opt_dummy,
) or usage();
usage() if $opt_help;


#############################################################################
### Main
#


### Local Variables:
### coding: utf-8
### End:
### vim:set ai et sts=2 sw=2 tw=0 fileencoding=utf-8:
