#!/usr/bin/zsh -f


#############################################################################
### Configuration

### Command paths (Full or relative paths accepted)


### Preferences

# [Optional] Turns on debugging
DEBUG=1

# [Optional] Specifies where temporary files will be created
# (such as those by =() )
TMPPREFIX="${TMP:-/tmp}/.${0##*/}-"

### End of configuration
#############################################################################


#############################################################################
### Init

arg0="${0##*/}"

### Usage

usage()
{
  <<END >&2
Usage: $arg0 [-h] [-d dummy] [file...]
       -h: get help
       -d dummy: you're a dummy
END
  exit 1
}

### Option defaults

opt_dummy=

### Options

while getopts ":hd:" opt; do
  case "$opt" in
    h)
      usage
      ;;
    d)
      case $OPTARG in
        dum1|dum2) opt_dummy=$OPTARG ;;
        *) usage ;;
      esac
      ;;
    *) 
      usage
      ;;
  esac
done

shift $(( $OPTIND - 1 ))

# Check that all arguments have been specified
(( $+opt_dummy != 1 )) && usage


#############################################################################
### Main


### Local Variables:
### coding: utf-8
### End:
### vim:set ai et sts=2 sw=2 tw=0:
